---
kind: pipeline
type: docker
name: project

steps:
- name: all
  image: plugin/docker
  settings:
    username: 
      from_secret: docker_username
    password: 
      from_secret: docker_password
    repo: stormweasel/drone-project
    auto_tag: true
    auto_tag_suffix: drone-build
