---
kind: pipeline
type: docker
name: project

steps:
- name: all
  image: plugin/docker
  enviroment:
    username: 
      from_secret: docker_username
    password:
      from_secret: docker_password
  settings:
    username: docker_username
    password: docker_password
    repo: stormweasel
    auto_tag: true
    auto_tag_suffix: drone-build
